-- [폐기됨 2026-08-12] 주간 응모권 랭킹 공개 RPC
--
-- 미션 인증 / 주간 응모권 추첨을 폐지하면서 이 함수는 DROP 했습니다.
-- 폐기 사유
--   1) 호출부(/winners 리더보드 탭)가 제거되어 더 이상 쓰이지 않습니다.
--   2) p_limit 상한이 없어 큰 값을 넣으면 해당 주 인증자 전원의 user_id·닉네임·집계값이 통째로 반환됐습니다.
--
-- 실제 적용된 마이그레이션: retire_mission_verification_and_weekly_raffle
--   update airdrop_tasks set status = 'ended' where status = 'active';
--   drop function if exists public.ticket_leaderboard(integer);
--
-- 미션 인증 INSERT 차단 방식
--   airdrop_submissions 의 subs_insert_own 정책이 'active' 상태 미션을 요구합니다.
--   따라서 진행중 미션을 모두 ended 로 내리는 것만으로 신규 인증이 DB 레벨에서 막힙니다.
--   기존 제출 기록(airdrop_submissions 6,207건)과 주간 당첨 기록(raffle_winners 97건)은 보존했습니다.
--
-- 되돌리려면 git 이력에서 이 파일의 이전 버전(CREATE OR REPLACE FUNCTION ...)을 복원한 뒤
-- 필요한 미션의 status 를 'active' 로 되돌리십시오.
